### ISSUE TITLE
Update AWS SDK

### ISSUE THREAD

**Issue by pcfens** [deliciousbrains/wp-migrations#7]
This issue is essentially the same as deliciousbrains/wp-amazon-s3-and-cloudfront#536. The same benefit of using an IAM role should work here too.

I'm attempting to use IAM roles linked to a Kubernetes service account to grant access to S3 instead of giving the entire node an IAM role. Amazon's documentation says that version 3.110.7 or newer of the PHP SDK is required. There have been bugfixes since then, so an update to the latest PHP SDK would be appreciated.

**Comment by polevaultweb** [comment]
@pcfens i think this is the wrong repo :)

**Comment by pcfens** [comment]
You're right - thanks!
